package main

import (
	"flag"
	"html/template"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"anid.dev/chronicle/internal/storage"
	"anid.dev/chronicle/internal/trip"
	"github.com/olivere/vite"
)

func main() {
	var (
		isDev = flag.Bool("dev", false, "run in development mode")
	)
	flag.Parse()

	if *isDev {
		runDevServer()
	} else {
		runProdServer()
	}
}

func runDevServer() {
	mux := http.NewServeMux()

	assets := http.FileServerFS(os.DirFS("."))

	mux.Handle("/src/assets/", assets)

	closeStorage := registerAPI(mux)
	defer closeStorage()

	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/" || r.URL.Path == "/index.html" || strings.HasPrefix(r.URL.Path, "/trip") {
			viteFragment, err := vite.HTMLFragment(vite.Config{
				FS:      os.DirFS("."),
				IsDev:   true,
				ViteURL: "http://localhost:5173",
			})
			if err != nil {
				http.Error(w, "Error instantiating vite fragment", http.StatusInternalServerError)
				return
			}

			tmpl, err := template.New("index").Parse(indexTmpl)
			if err != nil {
				http.Error(w, "Error parsing template", http.StatusInternalServerError)
				return
			}

			if err = tmpl.Execute(w, map[string]interface{}{
				"Vite": viteFragment,
			}); err != nil {
				http.Error(w, "Error executing template", http.StatusInternalServerError)
				return
			}
			return
		}

		// Serve files in the public directory. By default, these files are
		// referenced in the DOM with a root-relative URL format (e.g. '/file.ext').
		http.ServeFileFS(w, r, os.DirFS("./public"), filepath.Base(r.URL.Path))
	})

	server := &http.Server{
		Addr:    serverAddr(),
		Handler: mux,
	}

	log.Printf("Development server listening on http://%s", server.Addr)
	if err := server.ListenAndServe(); err != nil {
		panic(err)
	}
}

func runProdServer() {
	distFS := os.DirFS("./dist")

	mux := http.NewServeMux()

	assets := http.FileServerFS(distFS)

	// Handle requests for Vite-managed assets.
	mux.Handle("/assets/", assets)

	closeStorage := registerAPI(mux)
	defer closeStorage()

	mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		if r.URL.Path == "/" || r.URL.Path == "/index.html" {
			viteFragment, err := vite.HTMLFragment(vite.Config{
				FS:    distFS,
				IsDev: false,
			})
			if err != nil {
				http.Error(w, "Error instantiating vite fragment", http.StatusInternalServerError)
				return
			}

			tmpl, err := template.New("index").Parse(indexTmpl)
			if err != nil {
				http.Error(w, "Error parsing template", http.StatusInternalServerError)
				return
			}

			if err = tmpl.Execute(w, map[string]interface{}{
				"Vite": viteFragment,
			}); err != nil {
				http.Error(w, "Error executing template", http.StatusInternalServerError)
				return
			}
			return
		}

		// Serve the public files generated by Vite. By default, these files are
		// referenced in the DOM with a root-relative URL format (e.g. '/file.ext').
		http.ServeFileFS(w, r, distFS, filepath.Base(r.URL.Path))
	})

	server := &http.Server{
		Addr:    serverAddr(),
		Handler: mux,
	}

	log.Printf("Production server listening on http://%s", server.Addr)
	if err := server.ListenAndServe(); err != nil {
		panic(err)
	}
}

func registerAPI(mux *http.ServeMux) func() {
	store, err := storage.NewStorage()
	if err != nil {
		log.Fatalf("Failed to initialize database storage: %v", err)
	}

	log.Println("Database initialized and connected")

	tripHandler := trip.NewHandler(store)
	mux.Handle("/api/trips", tripHandler)
	mux.Handle("/api/trips/", tripHandler)

	return func() {
		if err := store.Close(); err != nil {
			log.Printf("Failed to close database storage: %v", err)
		}
	}
}

func serverAddr() string {
	host := os.Getenv("CHRONICLE_HOST")
	if host == "" {
		host = "localhost"
	}

	port := os.Getenv("CHRONICLE_PORT")
	if port == "" {
		port = "8572"
	}

	if _, err := strconv.Atoi(port); err != nil {
		log.Printf("Invalid CHRONICLE_PORT %q, defaulting to 8572", port)
		port = "8572"
	}

	return host + ":" + port
}

var indexTmpl = `<!doctype html>
<html lang="en" class="h-full scroll-smooth">
  <head>
    <meta charset="UTF-8" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600&display=swap" rel="stylesheet" />
		{{ .Vite.Tags }}
 </head>
  <body class="min-h-screen antialiased">
    <div id="root"></div>
  </body>
</html>
`
